[build]
  command = "yarn && yarn build"
  publish = "./build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  PYTHON_VERSION = "3.8"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "https://docs.testnet.vega.xyx/*"
  to = "https://docs.vega.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.fairground.vega.xyz/*"
  to = "https://docs.vega.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://vega-docusaurus.netlify.app/*"
  to = "https://docs.vega.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/testnet/grpc/*"
  to = "/testnet/api/grpc/:splat"
  status = 301

[[redirects]]
  from = "/docs/mainnet/grpc/*"
  to = "/mainnet/api/grpc/:splat"
  status = 301

[[redirects]]
  from = "/docs/testnet/graphql/*"
  to = "/testnet/api/graphql/:splat"
  status = 301

[[redirects]]
  from = "/docs/mainnet/graphql/*"
  to = "/mainnet/api/graphql/:splat"
  status = 301

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/testnet/api/vega-wallet/v2-api/get-started"
  to = "/testnet/api/vega-wallet/get-started"
  status = 301

[[redirects]]
  from = "/testnet/api/vega-wallet/v2-api"
  to = "/testnet/category/api/wallet-api"
  status = 301

[[redirects]]
  from = "/testnet/api/vega-wallet/v2-api/integrate-wallet-service"
  to = "/testnet/api/vega-wallet/how-to/bootstrap-local-service"
  status = 301

[[redirects]]
  from = "/testnet/api/vega-wallet/v2-api/openrpc"
  to = "/testnet/api/vega-wallet/reference/core/openrpc"
  status = 301
